/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DBModell;
import model.IModell;

/**
 *
 * @author monika.lohr
 */
public class Foablak extends javax.swing.JFrame {

 private Connection conn;
 private IModell model;
 
    public Foablak() {
        initComponents(); 
        setLocationRelativeTo(null);
        setTitle("Megrendelés ek kezelése v0.1");
        
        String connUrl="jdbc:mysql://localhost:3306/megrendelesek";
        String user="root";
        String pass="1234";
         
     try {
         conn= DriverManager.getConnection(connUrl, user, pass);
         model= new DBModell(conn);
     
     
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(rootPane, ex, "Adatbázis hiba", JOptionPane.ERROR_MESSAGE);
 
     }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mbFile = new javax.swing.JMenu();
        miKilepes = new javax.swing.JMenuItem();
        mbAdatok = new javax.swing.JMenu();
        miSzemelyek = new javax.swing.JMenuItem();
        miMegrendelesek = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbFile.setText("File");

        miKilepes.setText("Kilépés");
        miKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKilepesActionPerformed(evt);
            }
        });
        mbFile.add(miKilepes);

        jMenuBar1.add(mbFile);

        mbAdatok.setText("Adatok");

        miSzemelyek.setText("Személyek");
        miSzemelyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSzemelyekActionPerformed(evt);
            }
        });
        mbAdatok.add(miSzemelyek);

        miMegrendelesek.setText("Megrendelések");
        miMegrendelesek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMegrendelesekActionPerformed(evt);
            }
        });
        mbAdatok.add(miMegrendelesek);

        jMenuBar1.add(mbAdatok);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKilepesActionPerformed
     try {
         conn.close();
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(rootPane,ex,"Hibás a adatbázis", JOptionPane.ERROR_MESSAGE);
     } 
     System.exit(0);
    }//GEN-LAST:event_miKilepesActionPerformed

    private void miSzemelyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSzemelyekActionPerformed
        SzemelyekDialog szd= new SzemelyekDialog(this, model);
        szd.setVisible(true);
    }//GEN-LAST:event_miSzemelyekActionPerformed

    private void miMegrendelesekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMegrendelesekActionPerformed
       MegrendelsekDialog md = new MegrendelsekDialog(this, model);
       md.setVisible(true);
    }//GEN-LAST:event_miMegrendelesekActionPerformed
   
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbAdatok;
    private javax.swing.JMenu mbFile;
    private javax.swing.JMenuItem miKilepes;
    private javax.swing.JMenuItem miMegrendelesek;
    private javax.swing.JMenuItem miSzemelyek;
    // End of variables declaration//GEN-END:variables
}
